openapi: 3.0.3
info:
  title: SocialDistribution API
  version: 1.0.0
  description: A social networking app like X / Twitter
paths:
  /{uuid}/add-post:
    post:
      operationId: add_post_create
      description: |-
        Add post POST request called when create-post form is submitted.
        Adds a new post to database.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - add-post
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /add-profile:
    post:
      operationId: add_profile_create
      description: |-
        Add profile POST request called when create-profile form is submitted.
        Adds a new author profile to database.
      tags:
      - add-profile
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/authors:
    get:
      operationId: authors_retrieve
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/authors/{uuid}:
    get:
      operationId: authors_retrieve_2
      description: |-
        Edit profile using POST request, called when edit-profile form is submitted.
        Updates author fields if new input is provided to them.

        GET request, gets a single author's profile details.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: authors_create
      description: |-
        Edit profile using POST request, called when edit-profile form is submitted.
        Updates author fields if new input is provided to them.

        GET request, gets a single author's profile details.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{author_uuid}/posts/{post_id}/delete/:
    get:
      operationId: authors_posts_delete_retrieve
      description: Allows an author to delete their post.
      parameters:
      - in: path
        name: author_uuid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: authors_posts_delete_create
      description: Allows an author to delete their post.
      parameters:
      - in: path
        name: author_uuid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{author_uuid}/posts/{post_id}/edit/:
    get:
      operationId: authors_posts_edit_retrieve
      description: Allows an author to edit their post.
      parameters:
      - in: path
        name: author_uuid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: authors_posts_edit_create
      description: Allows an author to edit their post.
      parameters:
      - in: path
        name: author_uuid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{uuid}/follow/:
    post:
      operationId: authors_follow_create
      description: Send a follow request to another author.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{uuid}/follow-status/{foreign_author_uuid}/:
    get:
      operationId: authors_follow_status_retrieve
      description: Check if an author follows another
      parameters:
      - in: path
        name: foreign_author_uuid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{uuid}/followers/:
    get:
      operationId: authors_followers_retrieve
      description: Retrieve the list of followers for an author
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{uuid}/following/:
    get:
      operationId: authors_following_retrieve
      description: Retrieve the list of authors that the given author follows
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/{uuid}/friends/:
    get:
      operationId: authors_friends_retrieve
      description: Retrieve the list of mutual followers (friends) for an author
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /authors/search/:
    get:
      operationId: authors_search_retrieve
      description: Search authors by username or display name and render a results
        page.
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /comment/{comment_uuid}/like_comment/:
    post:
      operationId: comment_like_comment_create
      description: |-
        - Description: Like a comment
        - Returns a Json Response with the comment's like count (integer)
      parameters:
      - in: path
        name: comment_uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - comment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /post/{post_id}/add_comment/:
    post:
      operationId: post_add_comment_create
      description: Add a comment to a post
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - post
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /post/{post_id}/like_post/:
    post:
      operationId: post_like_post_create
      description: |-
        - Description: Like a post
        - Returns a Json Response with the post's like count (integer)
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - post
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /posts/{post_id}/unlisted:
    get:
      operationId: posts_unlisted_retrieve
      description: Allow anyone with the link to view an unlisted post.
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - posts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
